### PR TITLE
Update table.php

### PR DESCRIPTION
**Pull request by wannaco**
Responsive tables would be a great addition to mobile devices http://getbootstrap.com/css/#tables-responsive

### CODE REVIEW

**Comment by maskas** [comment]
There is a small problem. I doubt the result is better. Maybe it is a bit more correct, but less usable at the end of the day. The look without the fix:

scroll

The look with fix

scroll-with-fix

In both cases we do have the scroll. But when using the fix, the scroll is at the bottom of the page. So I have to scroll down, then scroll right, and then scroll back to top to see the results. That's like solving one problem and introducing another bigger one.

There must be a much better solution.

**Comment by wannaco** [comment]
That fix is intended for Mobile devices ( tablets and cellphones) primarily rather than re-sizing the browser in a desktop, cases in which you have a touch screen 99% of the time so a swipe does it all for you.

**Comment by maskas** [comment]
So the nicer solution would be to add that class only when the screen size is narrow. Agree?

**Comment by wannaco** [comment]
Agree totally. it would require tweaking some js in order to add a break point (media query)

**Pull request closed without merging**
