### PR TITLE
Fix multi-depth modal scroll

### PR DESCRIPTION
**Pull request by HalcyonD**
Check if any other modal dialog is still open before removing modal-open class from body. #691

### CODE REVIEW

**Comment by jankus** [comment]
Did you modify default Bootstrap library?

**Comment by HalcyonD** [comment]
Yeah :\ didn't find any other simple and efficient way without adding a bunch of code everywhere

**Comment by jankus** [comment]
Not good then. We do not modify 3rd party libraries. They will be overwritten with next version update and all changes lost.

If it's too complicated to implement automatic behavior, let's stick to manual one.

I believe the parent modal is aware that it is opening a secondary modal. When child is closed parent should handle this event and check whethet required CSS classes are in place.

What do you think?

**Comment by HalcyonD** [comment]
But right in the bootstrap.js it doesn't check anything when you call hide() it just instantly removes the class. I'll see if I can find a way in the IP js.

**Comment by jankus** [comment]
Parent should bint to "hidden.bs.modal" event on child modal instance.

**Comment by maskas** [comment]
Very nice stuf. Big thanks !!!

**Pull request merged**
