### PR TITLE
switch from MyISAM to InnoDB

### PR DESCRIPTION
**Pull request by Remo**
MyISAM is pretty limited, can't see any reason why InnoDB shouldn't be the default storage engine.

### CODE REVIEW

**Comment by maskas** [comment]
I don't know how it is at the moment. But earlier not all hosting providers allowed InnoDB. I'm a little scared to merge this pull request.

**Comment by Remo** [comment]
Pretty sure that's a thing of the past, these days every CMS/framework I came across uses InnoDB. MySQL 5.6 even supports fulltext indexes, that's probably the only benefit it had. InnoDB would also make it possible to add foreign keys at some points, making sure we don't have any issues with referential integrity.

**Comment by maskas** [comment]
I've just merged, but now I see, that those who update, will still have MyISAM, while those, who make a fresh install, will have InnoDB. It would be good to have a migration to make sure all websites are on sync.

**Comment by Remo** [comment]
Yes, indeed! I haven't done any research regarding the way you handle migrations. Feel free to open this, maybe I've got time in the future, but can't promise anything.

**Pull request merged**
