### PR TITLE
Fix modal backdrop height after tinymce init.

### PR DESCRIPTION
**Pull request by donnysim**
Fix modal backdrop height after tinymce init. #680

### CODE REVIEW

**Comment by maskas** [comment]
Where can I find this on default IP installation? I can't reproduce. 

If that was in the GIRD, maybe I've already fixed by this commit? https://github.com/impresspages/ImpressPages/commit/e744ceab8eb69b50d8e013976e36ccbcf4ce9289

**Comment by HalcyonD** [comment]
I don't really have anywhere to test it atm, but if you don't get this behaviour: #680 then I guess that commit fixed it.

**Comment by HalcyonD** [comment]
It also happened on in IP forms widget where richtext options were used which is why I've set the fix to be on `init_instance_callback`. I'm thinking that this will happen everywhere where tinymce is used in a modal.

**Comment by maskas** [comment]
I tried TinyMCE in GRID modal. no problems. Just checked contact form options config modal with TinyMCE. Also working just fine. Let's leave this for some time till we see if there are any issues with this.  
If there will be issues with this, I will rewrite this code to be in modal rather than TinyMCE config.

**Pull request closed without merging**
