### PR TITLE
Add validator pattern attribute for minlength javascript validation.

### PR DESCRIPTION
**Pull request by mrx**
Client side validation for min length validator.

### CODE REVIEW

**Comment by mrx** [comment]
@maskas there is an error in my code. I left out the comma after the number preventing input longer then minlength.

Correct code is:  'pattern="(.+){' . $this->minLength . ',}"';

Sorry!

**Comment by maskas** [comment]
By the way, why do we need plus sign and first brackets?

Why not just 'pattern=".{' . $this->minLength . ',}"'

**Comment by mrx** [comment]
pattern is a regex. Don't  ".+" matches everything, {4,} determines length min to max.

**Comment by maskas** [comment]
Cool now? https://github.com/impresspages/ImpressPages/blob/master/Ip/Form/Validator/MinLength.php

**Comment by mrx** [comment]
Yes, Thanks!

**Pull request merged**
